import type { LucideIcon } from "lucide-react";
import {
  Apple,
  Baby,
  Beef,
  Beer,
  Bird,
  Cake,
  Carrot,
  Cherry,
  ChefHat,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Cylinder,
  Droplets,
  Drumstick,
  Egg,
  Fish,
  Flame,
  FolderTree,
  Grid2x2,
  GlassWater,
  IceCream,
  IceCreamCone,
  Inbox,
  Leaf,
  Martini,
  Milk,
  Package,
  PillBottle,
  Pizza,
  Salad,
  Sandwich,
  Snowflake,
  Soup,
  UtensilsCrossed,
  Warehouse,
  Wheat,
  Wine,
} from "lucide-react";

/** Titre sans accents, minuscules. */
export function normalizeCategoryTitle(s: string): string {
  return s
    .normalize("NFD")
    .replace(/\p{M}/gu, "")
    .toLowerCase()
    .trim();
}

/** Mots alphanumériques (évite les faux positifs type « vin » dans « vinaigre »). */
function tokens(n: string): string[] {
  return n.split(/[^a-z0-9]+/).filter(Boolean);
}

type PhraseRule = { re: RegExp; Icon: LucideIcon };

/**
 * Phrases multi-mots ou expressions figées — évaluées en premier.
 */
const PHRASE_RULES: PhraseRule[] = [
  { re: /^sans rubrique$/i, Icon: Inbox },
  { re: /non classe|non-class|divers$/i, Icon: Inbox },
  { re: /fruits?\s+de\s+mer|plateau\s+de\s+mer/i, Icon: Fish },
  { re: /fromage\s+blanc|creme\s+fra[iî]che|creme\s+fraiche/i, Icon: Milk },
  { re: /petit[-\s]?dejeuner|brunch/i, Icon: Croissant },
  { re: /hors[-\s]?d['']?oeuvre|hors[-\s]?d['']?œuvre|entree\s+froide|entree\s+chaude/i, Icon: Soup },
  { re: /plat\s+du\s+jour|suggestion\s+du\s+chef/i, Icon: UtensilsCrossed },
  { re: /vin\s+(rouge|blanc|rose|mousseux|effervescent)/i, Icon: Wine },
  { re: /eau\s+(minerale|gazeuse|plate|du\s+robinet|petillante)/i, Icon: Droplets },
  { re: /the\s+(vert|noir|blanc|glace)/i, Icon: Leaf },
  { re: /bar\s+(de\s+)?ligne|filet\s+de\s+bar/i, Icon: Fish },
  {
    re: /glace\s+a\s+l['']?italienne|glace\s+italienne|glace\s+itali|gelato/i,
    Icon: IceCreamCone,
  },
];

/**
 * Correspondance par mot entier (clé = forme normalisée sans accent).
 * Ordre : plus long d’abord pour prioriser « champagne » sur « vin ».
 */
const TOKEN_ICONS: [string, LucideIcon][] = [
  // Vins & alcools (régions / appellations courantes)
  ["champagne", Wine],
  ["bourgogne", Wine],
  ["bordeaux", Wine],
  ["alsace", Wine],
  ["languedoc", Wine],
  ["provence", Wine],
  ["beaujolais", Wine],
  ["jura", Wine],
  ["savoie", Wine],
  ["loire", Wine],
  ["rhone", Wine],
  ["rhones", Wine],
  ["medoc", Wine],
  ["pomerol", Wine],
  ["graves", Wine],
  ["sancerre", Wine],
  ["muscadet", Wine],
  ["vins", Wine],
  ["vin", Wine],
  ["mousseux", Wine],
  ["effervescent", Wine],
  ["cidre", Apple],
  ["biere", Beer],
  ["bieres", Beer],
  ["ipa", Beer],
  ["stout", Beer],
  ["lager", Beer],
  ["pils", Beer],
  ["whisky", Martini],
  ["whiskey", Martini],
  ["vodka", Martini],
  ["gin", Martini],
  ["rhum", Martini],
  ["cognac", Martini],
  ["armagnac", Martini],
  ["calvados", Martini],
  ["pastis", Martini],
  ["absinthe", Martini],
  ["aperitif", Martini],
  ["digestif", Martini],
  ["cocktail", Martini],
  ["mojito", Martini],
  ["spritz", Martini],
  ["negroni", Martini],
  ["cafes", Coffee],
  ["cafe", Coffee],
  ["espresso", Coffee],
  ["ristretto", Coffee],
  ["cappuccino", Coffee],
  ["latte", Coffee],
  ["infusions", Leaf],
  ["infusion", Leaf],
  ["tisanes", Leaf],
  ["tisane", Leaf],
  ["rooibos", Leaf],
  ["matcha", Leaf],
  ["thes", Leaf],
  ["the", Leaf],
  ["eaux", Droplets],
  ["eau", Droplets],
  ["perrier", Droplets],
  ["badoit", Droplets],
  ["evian", Droplets],
  ["volvic", Droplets],
  ["contrex", Droplets],
  ["jus", GlassWater],
  ["nectar", GlassWater],
  ["smoothie", GlassWater],
  ["softs", CupSoda],
  ["soft", CupSoda],
  ["sodas", CupSoda],
  ["soda", CupSoda],
  ["cola", CupSoda],
  ["limonade", CupSoda],
  ["schweppes", CupSoda],
  ["pizza", Pizza],
  ["pizzas", Pizza],
  ["calzone", Pizza],
  ["sushis", Fish],
  ["sushi", Fish],
  ["makis", Fish],
  ["maki", Fish],
  ["sashimi", Fish],
  ["poke", Fish],
  ["ramens", Soup],
  ["ramen", Soup],
  ["pho", Soup],
  ["nouilles", Soup],
  ["udon", Soup],
  ["soba", Soup],
  ["woks", Soup],
  ["wok", Soup],
  ["curry", Soup],
  ["tajine", UtensilsCrossed],
  ["couscous", UtensilsCrossed],
  ["paella", UtensilsCrossed],
  ["tapas", Soup],
  ["mezze", Soup],
  ["antipasti", Salad],
  ["bruschetta", Salad],
  ["saumon", Fish],
  ["thon", Fish],
  ["cabillaud", Fish],
  ["lieu", Fish],
  ["sole", Fish],
  ["turbot", Fish],
  ["dorade", Fish],
  ["maquereau", Fish],
  ["sardine", Fish],
  ["anchois", Fish],
  ["moules", Fish],
  ["moule", Fish],
  ["huitres", Fish],
  ["huitre", Fish],
  ["crevettes", Fish],
  ["crevette", Fish],
  ["homard", Fish],
  ["langouste", Fish],
  ["crabe", Fish],
  ["crustaces", Fish],
  ["coquillages", Fish],
  ["tartare", Beef],
  ["carpaccio", Beef],
  ["entrecote", Beef],
  ["entrecotes", Beef],
  ["bavette", Beef],
  ["onglet", Beef],
  ["rumsteak", Beef],
  ["steak", Beef],
  ["boeuf", Beef],
  ["veau", Beef],
  ["agneau", Beef],
  ["gigot", Beef],
  ["gibier", Beef],
  ["canard", Bird],
  ["poulet", Bird],
  ["poulets", Bird],
  ["volaille", Bird],
  ["volailles", Bird],
  ["dinde", Bird],
  ["pintade", Bird],
  ["chapon", Bird],
  ["porc", Bird],
  ["cochon", Bird],
  ["jambon", Sandwich],
  ["charcuterie", Sandwich],
  ["saucisson", Sandwich],
  ["bacon", Sandwich],
  ["nuggets", Drumstick],
  ["nugget", Drumstick],
  ["wings", Drumstick],
  ["ailes", Drumstick],
  ["cuisses", Drumstick],
  ["pates", ChefHat],
  ["pate", ChefHat],
  ["pasta", ChefHat],
  ["carbonara", ChefHat],
  ["bolognaise", ChefHat],
  ["lasagne", ChefHat],
  ["ravioli", ChefHat],
  ["gnocchi", ChefHat],
  ["tagliatelle", ChefHat],
  ["penne", ChefHat],
  ["spaghetti", ChefHat],
  ["risotto", ChefHat],
  ["patates", Leaf],
  ["pommes", Leaf],
  ["frites", Leaf],
  ["legumes", Leaf],
  ["legume", Leaf],
  ["ratatouille", Leaf],
  ["poelee", Leaf],
  ["gratin", Leaf],
  ["primeur", Carrot],
  ["carotte", Carrot],
  ["tomate", Salad],
  ["tomates", Salad],
  ["concombre", Salad],
  ["salades", Salad],
  ["salade", Salad],
  ["crudites", Salad],
  ["crudite", Salad],
  ["fromages", Milk],
  ["fromage", Milk],
  ["laitier", Milk],
  ["laitiers", Milk],
  ["lait", Milk],
  ["yaourt", Milk],
  ["yaourts", Milk],
  ["beurre", Milk],
  ["creme", Milk],
  ["desserts", Cake],
  ["dessert", Cake],
  ["patisserie", Cake],
  ["patisseries", Cake],
  ["gateau", Cake],
  ["gateaux", Cake],
  ["tarte", Cake],
  ["tartes", Cake],
  ["moelleux", Cake],
  ["fondant", Cake],
  ["tiramisu", Cake],
  ["eclair", Cake],
  ["eclairs", Cake],
  ["baba", Cake],
  ["mousse", Cake],
  ["biscuits", Cookie],
  ["biscuit", Cookie],
  ["cookies", Cookie],
  ["cookie", Cookie],
  ["macaron", Cookie],
  ["chocolat", Cookie],
  ["praline", Cookie],
  ["gelato", IceCreamCone],
  ["glaces", IceCream],
  ["glace", IceCream],
  ["sorbets", IceCream],
  ["sorbet", IceCream],
  ["parfait", IceCream],
  ["fruits", Cherry],
  ["fruit", Cherry],
  ["pomme", Cherry],
  ["poire", Cherry],
  ["fraise", Cherry],
  ["cerise", Cherry],
  ["citron", Cherry],
  ["orange", Cherry],
  ["ananas", Cherry],
  ["mangue", Cherry],
  ["galettes", CookingPot],
  ["galette", CookingPot],
  ["crepes", CookingPot],
  ["crepe", CookingPot],
  ["gaufres", Grid2x2],
  ["gaufre", Grid2x2],
  ["waffles", Grid2x2],
  ["waffle", Grid2x2],
  ["bouteilles", PillBottle],
  ["bouteille", PillBottle],
  ["canettes", Cylinder],
  ["canette", Cylinder],
  ["viennoiseries", Croissant],
  ["viennoiserie", Croissant],
  ["boulangerie", Croissant],
  ["brioche", Croissant],
  ["croissants", Croissant],
  ["croissant", Croissant],
  ["baguette", Croissant],
  ["pain", Croissant],
  ["toasts", Croissant],
  ["toast", Croissant],
  ["oeuf", Egg],
  ["oeufs", Egg],
  ["omelette", Egg],
  ["brouille", Egg],
  ["cereales", Wheat],
  ["cereal", Wheat],
  ["granola", Wheat],
  ["muesli", Wheat],
  ["avoine", Wheat],
  ["sandwich", Sandwich],
  ["sandwichs", Sandwich],
  ["burger", Sandwich],
  ["burgers", Sandwich],
  ["wrap", Sandwich],
  ["wraps", Sandwich],
  ["panini", Sandwich],
  ["tacos", Sandwich],
  ["kebab", Sandwich],
  ["bbq", Flame],
  ["barbecue", Flame],
  ["grill", Flame],
  ["grillades", Flame],
  ["brasero", Flame],
  ["plancha", Flame],
  ["enfants", Baby],
  ["enfant", Baby],
  ["kids", Baby],
  ["junior", Baby],
  // Stock / réserve
  ["epicerie", Package],
  ["epices", Package],
  ["epice", Package],
  ["condiments", Package],
  ["condiment", Package],
  ["conserves", Package],
  ["conserve", Package],
  ["bocaux", Package],
  ["huile", Package],
  ["vinaigre", Package],
  ["farine", Package],
  ["sucre", Package],
  ["sel", Package],
  ["surgeles", Snowflake],
  ["surgele", Snowflake],
  ["congelateur", Snowflake],
  ["congel", Snowflake],
  ["frais", Snowflake],
  ["reserve", Warehouse],
  ["reserves", Warehouse],
  ["stock", Warehouse],
  ["entrepot", Warehouse],
  ["depot", Warehouse],
  ["boissons", CupSoda],
  ["boisson", CupSoda],
];

TOKEN_ICONS.sort((a, b) => b[0].length - a[0].length);

type RegexRule = { re: RegExp; Icon: LucideIcon };

/**
 * Dernière couche : motifs plus larges mais avec limites (pas de sous-chaîne « eau » dans « beaujolais »).
 */
const REGEX_TAIL: RegexRule[] = [
  { re: /bi[eè]re/i, Icon: Beer },
  { re: /caf[eé]|espresso|ristretto|allonge/i, Icon: Coffee },
  { re: /cocktail|spiritueux|ap[eé]ro(\s|$)/i, Icon: Martini },
  { re: /champagne|mousseux|cr[eé]mant|prosecco|cava/i, Icon: Wine },
  { re: /vin(\s|$)|vins(\s|$)|viticulteur/i, Icon: Wine },
  { re: /asiat|tha[iï]|viet|chinois|cor[eé]en|japon|nippon|tokyo|sichuan/i, Icon: Soup },
  { re: /poisson|filets?\s+de\s+mer|crustac|coquillag/i, Icon: Fish },
  { re: /viande|boucher|boeuf|bœuf|steak|entrec[oô]te|bavette|onglet|agneau|gigot/i, Icon: Beef },
  { re: /porc|cochon|jambon|charcut|saucisson|bacon/i, Icon: Sandwich },
  { re: /volaille|poulet|canard|dinde|pintade|chapon/i, Icon: Bird },
  { re: /p[aâ]tes?\s|pasta|carbonara|bolognaise|lasagne|ravioli|gnocchi/i, Icon: ChefHat },
  { re: /dessert|p[aâ]tisserie|chocolat|sucr[eé]/i, Icon: Cake },
  { re: /entree|entr[eé]e|starter|amuse/i, Icon: Soup },
  { re: /salade|crudit[eé]/i, Icon: Salad },
  { re: /sandwich|burger|wrap|panini|tacos/i, Icon: Sandwich },
  { re: /boisson|breuvage|drink/i, Icon: CupSoda },
  { re: /primeur|l[eé]gume|ratatouille|gratin/i, Icon: Leaf },
  { re: /fromage|laitier|yaourt|cr[eè]me(\s|$)|beurre/i, Icon: Milk },
  { re: /epicer|condiment|conserves?|bocaux|farine|sucre(\s|$)|\bhuile\b|\bvinaigre\b/i, Icon: Package },
  { re: /surgele|congel|froid|frais(\s|$)/i, Icon: Snowflake },
  { re: /entrepot|reserve|stock|depot/i, Icon: Warehouse },
];

const FALLBACK: LucideIcon = FolderTree;

function iconFromTokens(n: string): LucideIcon | null {
  const toks = tokens(n);
  const set = new Set(toks);
  for (const [key, Icon] of TOKEN_ICONS) {
    if (set.has(key)) return Icon;
  }
  return null;
}

/**
 * Icône Lucide pour un libellé de rubrique (nom affiché ou segment de chemin).
 */
export function resolveLucideIconForCategoryTitle(title: string): LucideIcon {
  const raw = title.trim();
  if (!raw) return FALLBACK;
  const n = normalizeCategoryTitle(raw);

  for (const { re, Icon } of PHRASE_RULES) {
    if (re.test(n)) return Icon;
  }

  const fromTok = iconFromTokens(n);
  if (fromTok) return fromTok;

  for (const { re, Icon } of REGEX_TAIL) {
    if (re.test(n)) return Icon;
  }

  return FALLBACK;
}
